package atos.manolito.entity;
// Generated 24-dic-2019 9:22:53 by Hibernate Tools 5.4.7.Final

import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Payrollconfig generated by hbm2java
 */
@Entity
public class Payrollconfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private int id;
	private String keyField;
	private String value;

	public Payrollconfig() {
	}

	public Payrollconfig(int id, String keyField, String value) {
		this.id = id;
		this.keyField = keyField;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKeyField() {
		return this.keyField;
	}

	public void setKeyField(String keyField) {
		this.keyField = keyField;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
