package atos.manolito.entity;
// Generated 23-dic-2019 15:25:32 by Hibernate Tools 5.4.7.Final

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Salaryranges generated by hbm2java
 */
@Entity
@Table(name="SALARYRANGES")
public class Salaryrange implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	private int id;
	private int range;
	private int retention;

	public Salaryrange() {
	}

	public Salaryrange(int id, int range, int retention) {
		this.id = id;
		this.range = range;
		this.retention = retention;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRange() {
		return this.range;
	}

	public void setRange(int range) {
		this.range = range;
	}

	public int getRetention() {
		return this.retention;
	}

	public void setRetention(int retention) {
		this.retention = retention;
	}

}
